---

- name: Set up SELinux permissive mode
  replace:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    replace: SELINUX=permissive
  tags:
    - selinux

- name: Install epel-release repo..
  yum: 
    name: epel-release
    state: present

- name: Install Python..
  yum:
    name: python
    state: present