---
sudo: required

services:
  - docker

before_install:
  - 'sudo docker pull centos:7'
  - 'sudo docker build --no-cache --rm --file=Dockerfile.centos-7 --tag=centos-7:ansible .'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible:ro centos-7:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/test.yml --syntax-check --skip-tags "ip_cnf","selinux" '
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/test.yml --skip-tags "ip_cnf","selinux"'
  - 'sudo docker rm -f "$(cat ${container_id})"'
